# Generated by Django 5.1.3 on 2025-04-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_punto_conoce_imagen_ruta"),
    ]

    operations = [
        migrations.AddField(
            model_name="punto_conoce",
            name="imagen_negocio",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes/"),
        ),
        migrations.AlterField(
            model_name="punto_conoce",
            name="imagen_ruta",
            field=models.CharField(max_length=255),
        ),
    ]
