# Generated by Django 5.1.3 on 2025-04-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_punto_conoce_imagen_negocio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto_conoce",
            name="imagen_negocio",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
