# Generated by Django 5.1.3 on 2025-04-21 03:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_punto_conoce_imagen_negocio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punto_conoce",
            name="imagen_negocio",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="imagen_negocio"
            ),
        ),
    ]
